-- seeds/dev/seed_issue_cards_dev.sql
-- 20 Development Seed Issue Cards covering common GST issues.
-- All cards are seeded with status = 'draft' and summary prefixed with '[DEV - not CA reviewed]'.

INSERT INTO issue_cards (card_id, version, title, summary, sections, period_from, period_to, stages, keywords, not_this_if, template_id, status)
VALUES
-- Pair 1: Section 73 (Routine Demand) vs Section 74 (Extended Period / Fraud)
('CARD-001', 1, 'Section 73 Routine Tax Demand without Suppression',
 '[DEV - not CA reviewed] Proposal of demand under Section 73 on routine return mismatches where no fraud, willful misstatement, or suppression of facts with intent to evade tax is alleged.',
 '["04 Issue-wise Response", "05 Para-wise Reply", "08 Ground 1"]'::jsonb,
 '2017-07-01', '2024-03-31', '["asmt_10", "drc_01a", "scn_73"]'::jsonb,
 '["section 73", "routine mismatch", "no suppression", "gstr-3b vs 2a"]'::jsonb,
 '["Notice explicitly invokes extended period under Section 74", "Notice alleges fraud, collusion, or deliberate misstatement"]'::jsonb,
 'TPL-SEC73-01', 'draft'),

('CARD-002', 1, 'Section 74 Extended Period Invocation Invalid without Fraud/Suppression',
 '[DEV - not CA reviewed] Invocation of extended period of limitation under Section 74 alleging fraud/suppression on routine return reconciliation without proving deliberate intent to evade tax.',
 '["04 Issue-wise Response", "05 Para-wise Reply", "08 Ground 1"]'::jsonb,
 '2017-07-01', '2024-03-31', '["scn_74"]'::jsonb,
 '["section 74", "extended period", "suppression", "intent to evade", "limitation"]'::jsonb,
 '["Notice is issued under Section 73", "Department has supplied positive evidence of willful concealment or fake invoices"]'::jsonb,
 'TPL-SEC74-01', 'draft'),

-- Pair 2: Section 16(4) Statutory Cut-off vs Section 16(5) Statutory Relaxation
('CARD-003', 1, 'Section 16(4) Input Tax Credit Time-Bar Disallowance',
 '[DEV - not CA reviewed] Disallowance of Input Tax Credit under Section 16(4) of the CGST Act for claims availed after 30th November following the end of financial year.',
 '["04 Issue-wise Response", "05 Para-wise Reply", "09 Ground 2"]'::jsonb,
 '2017-07-01', '2024-03-31', '["asmt_10", "drc_01a", "scn_73", "scn_74"]'::jsonb,
 '["section 16(4)", "itc time bar", "gstr-3b delayed filing", "30th november"]'::jsonb,
 '["Return pertains to FY 2017-18, 2018-19, 2019-20 or 2020-21 covered under Section 16(5) relaxation", "ITC was claimed in GSTR-3B filed before statutory due date"]'::jsonb,
 'TPL-SEC164-01', 'draft'),

('CARD-004', 1, 'Section 16(5) Statutory Relaxation of ITC Time-Bar for FY 2017-18 to 2020-21',
 '[DEV - not CA reviewed] Retrospective statutory relaxation under Section 16(5) allowing ITC claims for FY 2017-18, 2018-19, 2019-20, and 2020-21 in returns filed up to 30th November 2021.',
 '["04 Issue-wise Response", "05 Para-wise Reply", "09 Ground 2"]'::jsonb,
 '2017-07-01', '2021-03-31', '["asmt_10", "drc_01a", "scn_73", "scn_74"]'::jsonb,
 '["section 16(5)", "retrospective relaxation", "fy 2017-18", "fy 2018-19", "fy 2019-20", "fy 2020-21"]'::jsonb,
 '["Notice pertains to FY 2021-22 or later financial years", "GSTR-3B was filed after 30th November 2021"]'::jsonb,
 'TPL-SEC165-01', 'draft'),

-- Pair 3: GSTR-2A vs GSTR-2B ITC Mismatch
('CARD-005', 1, 'GSTR-3B vs GSTR-2A Auto-populated ITC Mismatch (Pre-Rule 36(4))',
 '[DEV - not CA reviewed] Disallowance of ITC based solely on mismatch between GSTR-3B and auto-populated GSTR-2A without verifying vendor tax payment or initiating supplier recovery.',
 '["04 Issue-wise Response", "05 Para-wise Reply", "09 Ground 2"]'::jsonb,
 '2017-07-01', '2020-12-31', '["asmt_10", "drc_01a", "scn_73"]'::jsonb,
 '["gstr-2a mismatch", "suncraft energy", "purchasing dealer", "supplier default"]'::jsonb,
 '["Notice period is post January 2022 governed strictly by Section 16(2)(aa) and GSTR-2B", "Supplier GSTIN is cancelled ab initio"]'::jsonb,
 'TPL-GSTR2A-01', 'draft'),

('CARD-006', 1, 'GSTR-3B vs GSTR-2B Static Statement Mismatch (Post January 2022)',
 '[DEV - not CA reviewed] Disallowance of ITC under Section 16(2)(aa) based on static statement GSTR-2B where invoices were communicated in subsequent return periods.',
 '["04 Issue-wise Response", "05 Para-wise Reply", "09 Ground 2"]'::jsonb,
 '2022-01-01', '2024-03-31', '["asmt_10", "drc_01a", "scn_73"]'::jsonb,
 '["gstr-2b", "section 16(2)(aa)", "static statement", "communication of itc"]'::jsonb,
 '["Notice period is prior to 1st January 2022", "Invoices are completely missing from supplier GSTR-1 returns"]'::jsonb,
 'TPL-GSTR2B-01', 'draft'),

-- Pair 4: Pre-SCN Intimation DRC-01A Defect vs Summary DRC-01 Notice Defect
('CARD-007', 1, 'Absence of Mandatory Pre-SCN Intimation in Form GST DRC-01A',
 '[DEV - not CA reviewed] Failure of the Proper Officer to issue pre-SCN intimation in Form GST DRC-01A under Rule 142(1A) prior to issuing Show Cause Notice.',
 '["07 Procedural Objections"]'::jsonb,
 '2017-07-01', '2022-10-14', '["scn_73", "scn_74"]'::jsonb,
 '["drc-01a", "pre-scn intimation", "rule 142(1a)", "procedural defect"]'::jsonb,
 '["DRC-01A intimation was actually issued and served", "Notice period is post Rule 142(1A) directory amendment"]'::jsonb,
 'TPL-DRC01A-01', 'draft'),

('CARD-008', 1, 'Bare Summary DRC-01 Notice Without Detailed Statement of Charges',
 '[DEV - not CA reviewed] Issuance of summary DRC-01 notice without providing itemized statement of facts, invoice reconciliation, or detailed grounds violating principles of natural justice.',
 '["07 Procedural Objections"]'::jsonb,
 '2017-07-01', '2024-03-31', '["asmt_10", "drc_01a", "scn_73", "scn_74"]'::jsonb,
 '["bare summary", "nkas services", "principles of natural justice", "no statement of facts"]'::jsonb,
 '["Detailed show cause notice annexures were attached with DRC-01", "Notice contains complete invoice-wise demand calculations"]'::jsonb,
 'TPL-DRC01-01', 'draft'),

-- Pair 5: E-Way Bill Portal Mismatch vs GSTR-1 / 3B Turnover Mismatch
('CARD-009', 1, 'E-Way Bill vs GSTR-3B Outward Taxable Supply Mismatch',
 '[DEV - not CA reviewed] Allegation of unrecorded turnover based solely on E-way bill generation data exceeding reported GSTR-3B sales without accounting for non-supply movement or cancelled e-way bills.',
 '["04 Issue-wise Response", "05 Para-wise Reply"]'::jsonb,
 '2018-04-01', '2024-03-31', '["asmt_10", "drc_01a", "scn_73"]'::jsonb,
 '["eway bill", "ewb mismatch", "goods movement", "gstr-3b turnover"]'::jsonb,
 '["Discrepancy is between GSTR-1 and GSTR-3B filings", "Consignment was accompanied by tax invoice without delivery challan"]'::jsonb,
 'TPL-EWB-01', 'draft'),

('CARD-010', 1, 'GSTR-1 Outward Supply vs GSTR-3B Tax Paid Mismatch',
 '[DEV - not CA reviewed] Difference between outward taxable turnover reported in GSTR-1 and self-assessed tax paid in GSTR-3B due to credit notes, amendment tables, or clerical errors.',
 '["04 Issue-wise Response", "05 Para-wise Reply"]'::jsonb,
 '2017-07-01', '2024-03-31', '["asmt_10", "drc_01a", "scn_73"]'::jsonb,
 '["gstr-1 vs 3b", "outward supply mismatch", "credit note adjustment", "table 9 amendments"]'::jsonb,
 '["Difference is based on E-way bill portal data", "Tax was unpaid in both GSTR-1 and GSTR-3B"]'::jsonb,
 'TPL-GSTR1-3B-01', 'draft'),

-- Cards 11 to 20: Other Common GST Issues
('CARD-011', 1, 'Interest Calculation Under Section 50 Restricted to Net Cash Liability',
 '[DEV - not CA reviewed] Demand of interest under Section 50 on gross tax liability instead of net tax paid via Electronic Cash Ledger as mandated by proviso to Section 50(1).',
 '["04 Issue-wise Response", "05 Para-wise Reply", "12 Quantum and Interest"]'::jsonb,
 '2017-07-01', '2024-03-31', '["asmt_10", "drc_01a", "scn_73", "scn_74"]'::jsonb,
 '["section 50", "interest on gross", "net cash ledger", "proviso to section 50(1)"]'::jsonb,
 '["Tax was paid out of Electronic Cash Ledger after statutory due date", "Balance in Electronic Credit Ledger was insufficient to cover tax liability"]'::jsonb,
 'TPL-SEC50-01', 'draft'),

('CARD-012', 1, 'Invalid Document Identification Number (DIN) on Communication',
 '[DEV - not CA reviewed] Communication or notice issued without verifiable Document Identification Number (DIN) in contravention of CBIC Circular No. 122/41/2019-GST.',
 '["07 Procedural Objections"]'::jsonb,
 '2019-11-05', '2024-03-31', '["asmt_10", "drc_01a", "scn_73", "scn_74"]'::jsonb,
 '["din invalid", "circular 122", "verifiable din", "invalid notice"]'::jsonb,
 '["Notice contains valid online verifiable DIN", "Communication is manual correspondence exempted under circular exception clause"]'::jsonb,
 'TPL-DIN-01', 'draft'),

('CARD-013', 1, 'Rule 36(4) Provisional ITC Cap Disallowance (5% / 10% / 20%)',
 '[DEV - not CA reviewed] Demand proposing recovery of excess provisional ITC claimed under Rule 36(4) during prescribed historical monthly cap periods.',
 '["04 Issue-wise Response", "05 Para-wise Reply"]'::jsonb,
 '2019-10-09', '2021-12-31', '["asmt_10", "drc_01a", "scn_73"]'::jsonb,
 '["rule 36(4)", "provisional itc cap", "10 percent cap", "20 percent cap"]'::jsonb,
 '["Notice period is post January 2022 when 100% GSTR-2B matching became mandatory", "Notice period is prior to 9th October 2019"]'::jsonb,
 'TPL-RULE364-01', 'draft'),

('CARD-014', 1, 'Ineligible ITC on Personal Consumption or Blocked Credit under Section 17(5)',
 '[DEV - not CA reviewed] Proposal to disallow ITC alleging blocked credit under Section 17(5) on motor vehicles, catering, or employee benefits used in furtherance of business.',
 '["04 Issue-wise Response", "05 Para-wise Reply"]'::jsonb,
 '2017-07-01', '2024-03-31', '["asmt_10", "drc_01a", "scn_73", "scn_74"]'::jsonb,
 '["section 17(5)", "blocked credit", "personal consumption", "furtherance of business"]'::jsonb,
 '["Goods were exclusively used for personal non-business use", "Goods were lost, stolen, destroyed, or written off"]'::jsonb,
 'TPL-SEC175-01', 'draft'),

('CARD-015', 1, 'Export of Goods / Services Refund Rejection (Form GST RFD-08)',
 '[DEV - not CA reviewed] Show cause notice RFD-08 proposing rejection of unutilized ITC refund on zero-rated exports alleging non-realization of BRC or FIRC within timeline.',
 '["04 Issue-wise Response", "05 Para-wise Reply"]'::jsonb,
 '2017-07-01', '2024-03-31', '["rfd_08"]'::jsonb,
 '["rfd-08", "export refund", "zero rated supply", "brc firc", "lut export"]'::jsonb,
 '["Notice is a routine ASMT-10 or SCN under Section 73", "Export proceeds were not realized within RBI extension period"]'::jsonb,
 'TPL-RFD08-01', 'draft'),

('CARD-016', 1, 'Reverse Charge Mechanism (RCM) Liability on Freight / Legal Services',
 '[DEV - not CA reviewed] Proposed demand under Section 9(3) for non-payment of RCM tax on GTA freight, legal services, or director remuneration where tax was paid in cash and ITC claimed.',
 '["04 Issue-wise Response", "05 Para-wise Reply"]'::jsonb,
 '2017-07-01', '2024-03-31', '["asmt_10", "drc_01a", "scn_73"]'::jsonb,
 '["rcm demand", "section 9(3)", "gta freight", "director remuneration", "legal services"]'::jsonb,
 '["Supplier billed under Forward Charge Mechanism", "GTA exercised option to pay under forward charge at 5% / 12%"]'::jsonb,
 'TPL-RCM-01', 'draft'),

('CARD-017', 1, 'Discrepancy in ASMT-10 Intimation Without Issuing Order / Proceeding Closure',
 '[DEV - not CA reviewed] Issuance of SCN directly without considering taxpayer reply submitted to ASMT-10 discrepancy intimation under Rule 99.',
 '["07 Procedural Objections"]'::jsonb,
 '2017-07-01', '2024-03-31', '["scn_73", "scn_74"]'::jsonb,
 '["asmt-10 reply", "rule 99", "asmt-12 closure", "unconsidered reply"]'::jsonb,
 '["Taxpayer failed to respond to ASMT-10 within 30 days", "ASMT-12 acceptance order was issued by Proper Officer"]'::jsonb,
 'TPL-ASMT10-01', 'draft'),

('CARD-018', 1, 'Cancellation of Registration of Selling Dealer with Retrospective Effect',
 '[DEV - not CA reviewed] Denial of genuine ITC to recipient purchasing dealer solely on account of retrospective cancellation of supplier GSTIN after completion of transaction.',
 '["04 Issue-wise Response", "05 Para-wise Reply", "09 Ground 2"]'::jsonb,
 '2017-07-01', '2024-03-31', '["asmt_10", "drc_01a", "scn_73", "scn_74"]'::jsonb,
 '["retrospective cancellation", "supplier cancelled", "genuine buyer", "e-way bill proof"]'::jsonb,
 '["Transaction is proven to be non-existent or paper transaction", "Buyer failed to produce tax invoice and proof of payment"]'::jsonb,
 'TPL-RETRO-01', 'draft'),

('CARD-019', 1, 'Classification Discrepancy & HSN Code Rate Difference Demand',
 '[DEV - not CA reviewed] Proposed differential tax demand alleging incorrect HSN classification or lower GST rate adoption without proving misclassification under Tariff Rules.',
 '["04 Issue-wise Response", "05 Para-wise Reply"]'::jsonb,
 '2017-07-01', '2024-03-31', '["asmt_10", "drc_01a", "scn_73"]'::jsonb,
 '["hsn classification", "gst rate difference", "customs tariff", "general rules of interpretation"]'::jsonb,
 '["Specific advance ruling exists against the taxpayer product", "Rate change notification explicitly covered the item"]'::jsonb,
 'TPL-HSN-01', 'draft'),

('CARD-020', 1, 'Exempted Supply Turnover Ineligible ITC Reversal under Rule 42 / 43',
 '[DEV - not CA reviewed] Demand alleging non-reversal of common Input Tax Credit attributable to exempt supplies or non-taxable turnover under Rule 42 and Rule 43.',
 '["04 Issue-wise Response", "05 Para-wise Reply"]'::jsonb,
 '2017-07-01', '2024-03-31', '["asmt_10", "drc_01a", "scn_73"]'::jsonb,
 '["rule 42", "rule 43", "exempt supply reversal", "common credit"]'::jsonb,
 '["Taxpayer makes 100% taxable supplies without exempt turnover", "Reversal was completed in annual return GSTR-9"]'::jsonb,
 'TPL-RULE42-01', 'draft')
ON CONFLICT (card_id, version) DO UPDATE SET
    title = EXCLUDED.title,
    summary = EXCLUDED.summary,
    sections = EXCLUDED.sections,
    period_from = EXCLUDED.period_from,
    period_to = EXCLUDED.period_to,
    stages = EXCLUDED.stages,
    keywords = EXCLUDED.keywords,
    not_this_if = EXCLUDED.not_this_if,
    template_id = EXCLUDED.template_id,
    status = EXCLUDED.status;
